### ISSUE TITLE
Is this project deprecated?

### ISSUE THREAD

**Issue by cheerun** [angular/react-native-renderer#100]
Hi, I'm interesting to use react native with angular 2,

but this project is stopped developing 2 month ago..
I want to know this project's roadmap.. then I decide either using it or transiting to Native Script.

**Comment by mlaval** [comment]
This project is experimental, it is not under active development.
Currently, it is only maintained to continue working with the latest versions of Angular and React Native.

**Comment by cheerun** [comment]
@mlaval 
Thank you so much!
