### ISSUE TITLE
Is it possible to use react-native-renderer for Angular 4?

### ISSUE THREAD

**Issue by m98** [angular/react-native-renderer#103]
Hello,

The title of the repository in the readme file is **[angular2-react-native](https://github.com/angular/react-native-renderer#angular2-react-native)**, and it seems it's just for Angular 2, otherwise, you could say **angular-react-native**.

Then, if I get it right that this is just supporting Angular 2 for now?

Thanks a lot,
I wish I can use react-native-renderer in the feature.

**Comment by mlaval** [comment]
The project has been migrated to Angular 4: 40f8e097d79df0ae5641f4c111278b428f2909dc
The naming has also been updated from "Angular 2" to simply "Angular": 5e00780f828ebff6394074d0293823b8c0811654
