### ISSUE TITLE
Android compatibility

### ISSUE THREAD

**Issue by toepoke** [angular/react-native-renderer#13]
Hi,

Are there any plans to support Android (or ****cough**** Windows Phone).

More curiosity than an actual request.

Many thanks,
Franz.

**Comment by mlaval** [comment]
With the new version, Android is now supported!

About Windows Phone, see this announcement: https://blogs.windows.com/buildingapps/2016/04/13/react-native-on-the-universal-windows-platform/
Once it is available in React Native itself, it should be possible to support it here.
