### ISSUE TITLE
Error: Cannot find module 'angular2-react-native/tools/copy-dependencies'

### ISSUE THREAD

**Issue by volkrass** [angular/react-native-renderer#19]
Followed this instruction:

git clone https://github.com/mlaval/angular2-react-native-seed.git
cd angular2-react-native-seed
npm install -g gulp react-native-cli typings
npm install
gulp init

This error occurs:
[14:13:02] Using gulpfile ~/Projects/experiments/react_tuts/angular2-react-native-seed/gulpfile.js
[14:13:02] Starting 'clean'...
[14:13:08] Finished 'clean' after 6.38 s
[14:13:08] Starting '!create'...
This will walk you through creating a new React Native project in /Users/devuser/Projects/experiments/react_tuts/angular2-react-native-seed/dist/ngRnSeed

Installing react-native package from npm...

Setting up new React Native app in /Users/devuser/Projects/experiments/react_tuts/angular2-react-native-seed/dist/ngRnSeed

ngRnSeed@0.0.1 /Users/devuser/Projects/experiments/react_tuts/angular2-react-native-seed/dist/ngRnSeed
└─┬ react@0.14.8 
  ├─┬ envify@3.4.0 
  │ └─┬ jstransform@10.1.0 
  │   ├── base62@0.1.1 
  │   ├── esprima-fb@13001.1001.0-dev-harmony-fb 
  │   └── source-map@0.1.31 
  └─┬ fbjs@0.6.1 
    └── whatwg-fetch@0.9.0 

[14:17:34] Finished '!create' after 4.42 min
[14:17:34] Starting 'init'...
[14:17:34] 'init' errored after 1.7 ms
[14:17:34] Error: Cannot find module 'angular2-react-native/tools/copy-dependencies'

Any thoughts?

**Comment by mlaval** [comment]
You should have this file `./node_modules/angular2-react-native/tools/copy-dependencies.js`. Otherwise, it seems that something went wrong during the `npm install`.
I just tried the instructions again it and it was successful.

**Comment by volkrass** [comment]
Ok, started from scratch again. Followed your instruction again.
$ git clone https://github.com/mlaval/angular2-react-native-seed.git
$ cd angular2-react-native-seed
$ npm install -g gulp react-native-cli typings
...
/usr/local/lib
├── gulp@3.9.1 
├── react-native-cli@0.2.0 
└── typings@0.7.12 
$ npm install
npm ERR! cb() never called!

**Comment by volkrass** [comment]
Reinstalled node, now it works. Sorry I got you bothered with my node problems.

**Comment by mlaval** [comment]
It seems that you were facing this issue: https://github.com/angular/angular/issues/8053
Moving to the latest node was the right thing to do.
