### ISSUE TITLE
TextInput clear text

### ISSUE THREAD

**Issue by denkomanceski** [angular/react-native-renderer#24]
Which is the best practice to clear the text inside textinput ? I can see that the component has [value] and [defaultValue] properties but  none of them seem to work. Also in the sample MVC application, when I submit the todo I want the textinput to be cleared.

Thanks

P.S. I am very excited about this project. I believe it has really big potential and I will try to contribute to it as much as I can :)

**Comment by mlaval** [comment]
This was a bug, setting the `value` property now correctly updates the field.
