### ISSUE TITLE
add unit and integration tests

### ISSUE THREAD

**Issue by tbosch** [angular/react-native-renderer#3]
E2e tests: try to use [Appium](https://saucelabs.com/appium) and run tests on Saucelabs
Unit tests: Mock out ReactNative and test the renderer functionality in isolation, e.g. via karma

Use [Travis](https://travis-ci.org/) for running the tests
Work with @yjbanov on this.

**Comment by uber5001** [comment]
Unit tests added in 2fe9c0bcfe4a530bf20eb7219b563a7937069972. E2e tests added in c0341abe177b090a6c999a91e354bb82b5e39b6e. Travis CI with e2e tests on Sauce added in 85d212119c8d4d1109894661de6102787d568f59.
