### ISSUE TITLE
state of the project and ability to use extensions

### ISSUE THREAD

**Issue by itsmeprasanjit** [angular/react-native-renderer#37]
I am curious if it is possible to use react native extensions with this project or create our custom extensions.And should i use this project for my next android and IOS project what are your recommendations ?

**Comment by mlaval** [comment]
Extensibility is clearly one of the hot topic for this project, I've created issue #48 to track it. The amount of time I can dedicate is unfortunately limited, so not sure how fast it will move.

To answer your question, it really depends on the complexity of your application, your time to market and your will to contribute to the project.
