### ISSUE TITLE
Do performance tests

### ISSUE THREAD

**Issue by tbosch** [angular/react-native-renderer#4]
First manual, i.e. just deploy todo app on a real device and check whether it is janky.

Then try to get numbers in a more automated way (e.g. FPS, start up time)

**Comment by tbosch** [comment]
TODO: add link to video

**Comment by uber5001** [comment]
Videos are in the repo: [iPhone 4](https://github.com/angular/react-native-renderer/blob/master/Angular%20React%20Native%20animations%20iPhone%204.mp4) and [iPad 2](https://github.com/angular/react-native-renderer/blob/master/Angular%20React%20Native%20animations.mp4)
