### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by savvaoff** [angular/react-native-renderer#68]
I'm sorry, is it the proper way to use the package for new projects:
1. prepare environment: https://github.com/angular/react-native-renderer#preparing-your-environment
2. clean up /sample
3. put project code in /sample (and only there)
4. run/deploy it.

PS.
as i see sample is partly hardcoded to the builder code:
https://github.com/angular/react-native-renderer/blob/master/gulpfile.js#L72

PPS.
do you plan to make "react-native-renderer" be usable as "pure" module/tool, to not keep its code with all the projects (project repos)?

thanks and sorry, if i do something a really wrong way.
@mlaval

**Comment by mlaval** [comment]
This project is published as a NPM package which can be used in a project: https://www.npmjs.com/package/angular2-react-native
Here is an example on how to use it: https://github.com/mlaval/angular2-react-native-seed

I would recommend to start by cloning this seed and then building your own project.
