### ISSUE TITLE
http.get( localhost )

### ISSUE THREAD

**Issue by lakstap** [angular/react-native-renderer#73]
I am trying to access a restful service returns JSON object,  works fine with wiki url but failing when i try to access http://localhost:3000. is there something i should do for this.

**Comment by lakstap** [comment]
i am running react-native application in android device

**Comment by six006** [comment]
http://localhost:3000  replact 'localhost' to domain or ip .

**Comment by mlaval** [comment]
Please follow @six006 advice.

**Comment by lakstap** [comment]
this issue is not resolved yet. i tried all options, network within company nothing works with http.get or fetch in angular 2 react native app
