### ISSUE TITLE
http.get or fetch within company network

### ISSUE THREAD

**Issue by lakstap** [angular/react-native-renderer#74]
I am trying to access a restful service returns JSON object, works fine with wiki url but failing when i try to access http://localhost:3000. is there something i should do for this.
this issue is not resolved yet. i tried all options, network within company nothing works with http.get or fetch in angular 2 react native app

**Comment by mlaval** [comment]
I'm not sure we can help with your connectivity problems.
Are you able to access the server from the browser of your Android device?
Can you post the code snippet where you use http.get?

**Comment by lakstap** [comment]
please close this issue. it is fixed.
