### ISSUE TITLE
How do we display icons in this framework.

### ISSUE THREAD

**Issue by lakstap** [angular/react-native-renderer#75]
i tried using md-icon, but it is not displaying the icon.

**Comment by mlaval** [comment]
You'll have to use the Image component: http://angular.github.io/react-native-renderer/image.html

If you use these icons extensively, you may want to create your own components to make it easier. Basically it would be the Angular version of https://github.com/oblador/react-native-vector-icons

**Comment by lakstap** [comment]
I have tried the react native vector icons, it is not displaying the icon
