### ISSUE TITLE
React Native Icons are not loading, Please do not close the issue, until we are sure it is fixed

### ISSUE THREAD

**Issue by lakstap** [angular/react-native-renderer#78]
<View  [styleSheet]="styles.ratingContainer">
                            <StarRating
                                disabled="false"
                                maxStars="10"
                                starColor="'#fb8c00'"
                                rating="7"
                                selectedStar="onSelectedRating()"
                              ></StarRating>
                     </View>
"dependencies": {
    "react-native-button": "^1.6.0",
    "react-native-vector-icons": "^2.0.3"
  },

npm install react-native-star-rating --save 
here is the example i tried , it is not loading the stars.

**Comment by mlaval** [comment]
These packages are React components, you cannot use them in an Angular 2 application.

The extensibility issue is a known one and is already tracked in https://github.com/angular/react-native-renderer/issues/48
Closing this issue as duplicate.
