### ISSUE TITLE
Author: App Settings

### ISSUE THREAD

**Issue by lakstap** [angular/react-native-renderer#83]
How to read/write in to app settings? i want to add an field in to the settings so that my app can read from the settings.

**Comment by lakstap** [comment]
i dont want to see the custom page instead if we go settings > apps > pick my app > i would like to see there?

**Comment by mlaval** [comment]
You'll need to create a standard Settings bundle as part of the iOS project generated: https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/UserDefaults/Preferences/Preferences.html

Then, accessing these settings seems to be possible from the react native application: http://stackoverflow.com/questions/39081688/open-settings-app-from-another-app-in-ios-react-native

To be experimented
