### ISSUE TITLE
How to load external template

### ISSUE THREAD

**Issue by jonathanyee** [angular/react-native-renderer#87]
```
@Component({
    selector: 'as-users',
    templateUrl: './users.html'
})
```
I get `console.error: "Unhandled Promise rejection:", "Failed to load users.html", "; Zone: ", "", "; Task:", "Promise,then", "; Value:', "Failed to load users.html", undefined.

`users.html` is in the same directory as this component

**Comment by mlaval** [comment]
This is not possible at run time, but it can be done at build time:
 - with JIT compilation, templates should be inlined as a build step 
 - with AOT compilation, the Angular compiler should take care of the templates. To be tried when this feature is ready, see #86
