### ISSUE TITLE
How to integrating angular 2 with an existing iOS/Android application?

### ISSUE THREAD

**Issue by gnaykcin** [angular/react-native-renderer#88]
Thank you for your effort to bring this cool library. I'm just learning about angular2 and native development. Do we have examples about integrating it with an existing iOS/Android application like [this](https://github.com/dsibiski/react-native-hybrid-app-examples) ?

**Comment by mlaval** [comment]
Never tried, this is a topic to be explored.

Please report any useful findings :)
