### ISSUE TITLE
ListView Component

### ISSUE THREAD

**Issue by jonathanyee** [angular/react-native-renderer#89]
Is ListView available as a component? I couldn't find it anywhere in the docs or the source

**Comment by mlaval** [comment]
In React Native, ListView is a custom component, which means it is not a direct wrapper to a native component, but a "pure" JavaScript React component.

Such components can not be used in an Angular context.
They would have to be reimplemented as Angular components, but there is no plan to do so.
#48 may also solve this issue if a technical solution can be found.
