### ISSUE TITLE
Android APK/Application size too large even for "Hello World" text using Angular2 + React Native 

### ISSUE THREAD

**Issue by sweety-wo** [angular/react-native-renderer#94]
When i create APK with "Hello World" text using Angular2 + React Native, generated APK is of 4.00MB+ when using "splits enable true" and when i try installing that APK in some android device...application installed is of 24.00MB+.

So i am not sure what is taking this much space when i am just printing hello world text using this project. My main concern here is of installed application size..that really seems large to me.

Is it normal to create application with 24.00MB+ when APK size is of 4.00MB+?

Can you please let me know how can i reduce this APK/Application sizes?

Thanks.

**Comment by mlaval** [comment]
This is an issue for react-native itself, it is not related to Angular.
Please open it on https://github.com/facebook/react-native

**Comment by sweety-wo** [comment]
okies..thanks..
