### ISSUE TITLE
Unknow named module:‘react/lib/ReactNativeEventEmitter’

### ISSUE THREAD

**Issue by optimistic-wyl** [angular/react-native-renderer#99]
![1-](https://cloud.githubusercontent.com/assets/17997932/21213387/f1dbed02-c2ce-11e6-8d54-8a1a938e748b.jpg)

Is this a problem of react native's version???

**Comment by informixter** [comment]
you have solutions ?

**Comment by mlaval** [comment]
Fixed by a878de11b7b6fd6b5798b81aff5c5c7dbffb1500
